spring:
  application:
    name: xwrGateway

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）如果没有配置密码就不要写这个属性了
    password: aoyox
    #连接池
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 60000ms
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
    #连接超时时间（毫秒）
    timeout: 10000ms
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes: # 配置路由
        - id: xwrWebSocket
          # 动态路由：从注册中心获取对应服务的实例
          uri: ws://localhost:8203/mq
          # 当断言成功后，交给某一个微服务处理时使用的是转发
          predicates:
            - Path=/ws/**
#          filters:
#            # 断言成功后，交给具体的 uri 对应的微服务处理，将 uri 的第一个参数去掉
#            - StripPrefix=1
        - id: xwrOpenFeign
          # 动态路由：从注册中心获取对应服务的实例
          uri: http://localhost:8210/
          # 当断言成功后，交给某一个微服务处理时使用的是转发
          predicates:
            - Path=/xwr*/**
#          filters:
#            # 断言成功后，交给具体的 uri 对应的微服务处理，将 uri 的第一个参数去掉
#            - StripPrefix=1

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8200/eureka/

