spring:
  bus:
    enabled: true
    trace:
      enabled: true

  jackson:
    default-property-inclusion: non_null

  jmx:
    enabled: false

  datasource:
    name: aoyox
    url: jdbc:mysql://192.168.3.3:3306/xwrERP?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: aoyox
    password: aoyox2019
    #    privateKey: MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAnBkQPqXCc8vwUw1PnhL3k0qM38HzOXJk+Qdlst5ybui46g+TDICngdoMTC15lDj0AaLnNsTbzeAvYrIVOnUctwIDAQABAkAatbcv4REq20SeEXMEK16tl14Pk5JYzBg2/GsMdj/Cdk3a09hsBA/PucJ/OGJIrFKjo3sGSGGTtTOCmRpa5bYRAiEA+BEUp7NkCX4WrmFkjTUMW9anv2+9YaGcgmBqxTdUcJ0CIQChFwj/tuFzDl2L028UzMiHjK9NuVh58U2Z7cO06ibQYwIhAJx7QdlL2zX1uN8FhsVgikxAiw7CsOcuaCkCIzgG4BgtAiAdQU+zEQV0ncFDaYyc3Gv2oggcN3LoAnizYcjPDE8sPQIgKa+k1qTYy+w75R5dd2XIOGsbu/HFjT1XaUChPUfvxmA=
    publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJwZED6lwnPL8FMNT54S95NKjN/B8zlyZPkHZbLecm7ouOoPkwyAp4HaDEwteZQ49AGi5zbE283gL2KyFTp1HLcCAwEAAQ==
    #    password: cBtDv596JbJIk4hApqGsDdWQizY3CIGvoGYtzSnHya35fPdal6c+QrtxCS8MaufMLL2+GmLWPvB0jjf/fk/QJA==
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5  # 初始化大小
      min-idle: 5  # 最小
      max-active: 100  # 最大
      max-wait: 60000  # 连接超时时间
      time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000  # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
      validationQuery: select 'x'
      test-while-idle: true  # 当连接空闲时，是否执行连接测试
      test-on-borrow: false  # 当从连接池借用连接时，是否测试该连接
      test-on-return: false  # 在连接归还到连接池时是否测试该连接
      filters: config,wall,stat  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20
      connectionProperties: druid.stat.slowSqlMillis=200;druid.stat.logSlowSql=true;config.decrypt=false;config.decrypt.key=${spring.datasource.public-key}
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 123456
      log4j2:
        enabled: true

  mybatis:
    #    mapper-locations: classpath*:mapper/**/*.xml
    #实体扫描，多个package用逗号或者分号分隔
    #    typeAliasesPackage: com.xwr.xwrBasic.dao
    global-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      db-column-underline: false
      #刷新mapper 调试神器
      refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      # Sequence序列接口实现类配置
      #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
      #自定义SQL注入器
      # sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
      call-setters-on-nulls: true

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.3.3
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）如果没有配置密码就不要写这个属性了
    password: aoyox
    #连接池
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 60000ms
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
    #连接超时时间（毫秒）
    timeout: 10000ms


#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: admin
#    password: aoyox2019

#  devtools:
#    restart:
#      enabled: true

      #      additional-paths: src/main/java/com/aoyox/basic
#      exclude: application.yml

#  security:   # 开启后http访问时需要用户名密码 否则访问接口时提示跨域问题
#    basic:
#      enabled: true
#    user:
#      #这是config-server的用户名和密码
#      name: root
#      password: aoyox2019
rocketmq:
  name-server: 192.168.3.3:9876

logging:
  config: classpath:log4j2.xml


eureka:
  instance:
    hostname: 192.168.3.3
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8200/eureka/

#endpoints:
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true
#  health:
#    sensitive: false