spring:
  application:
    name: xwrWebSocket
  jmx:
    enabled: false
#  devtools:
#    restart:
#      enabled: true
logging:
  config: classpath:log4j2.xml

eureka:
  instance:
    hostname: 192.168.3.3
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8200/eureka/
#    register-with-eureka: false
#    fetch-registry: false

