spring:
  application:
    name: xwrWebSocket
  jmx:
    enabled: false

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.3.3
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）如果没有配置密码就不要写这个属性了
    password: aoyox
    #连接池
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 60000ms
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
    #连接超时时间（毫秒）
    timeout: 10000ms
logging:
  config: classpath:log4j2.xml

eureka:
  instance:
    hostname: 192.168.3.3
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8200/eureka/
#    register-with-eureka: false
#    fetch-registry: false

