spring:
  application:
    name: xwrOpenFeign
  jmx:
    enabled: false
#  devtools:
#    restart:
#      enabled: true

eureka:
  instance:
    hostname: 172.19.246.166
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8200/eureka/
#    register-with-eureka: false
#    fetch-registry: false

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
