spring:
  application:
    name: xwrOpenFeign
  jmx:
    enabled: false

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8200/eureka/
#    register-with-eureka: false
#    fetch-registry: false

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
