spring:
  application:
    name: xwrConfigServer
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
    #      server:
#        git:
#          #这是其他项目配置文件的git仓库地址
##          uri: https://github.com/mar105/erpConfigProfile.git
#          uri: https://github.com/mar105/xwrConfigServer.git
#          searchPaths: '{application}'
    bus:
      enabled: true
      trace:
        enabled: true

  jmx:
    enabled: false

#http://localhost:8201/actuator使用这个看开放接口
management:
  endpoints:
    web:
      exposure:
        include: busrefresh

server:
  port: 8201
eureka:
  instance:
    hostname: 192.168.3.3
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8200/eureka/ #docker tomcat
#      defaultZone: http://${eureka.instance.hostname}:8200/eureka/  #项目直接启动


